/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AvailableWorkflowConnectRule
 */
public class AvailableWorkflowConnectRuleTest {
    private final AvailableWorkflowConnectRule model = new AvailableWorkflowConnectRule();

    /**
     * Model tests for AvailableWorkflowConnectRule
     */
    @Test
    public void testAvailableWorkflowConnectRule() {
        // TODO: test AvailableWorkflowConnectRule
    }

    /**
     * Test the property 'addonKey'
     */
    @Test
    public void addonKeyTest() {
        // TODO: test addonKey
    }

    /**
     * Test the property 'createUrl'
     */
    @Test
    public void createUrlTest() {
        // TODO: test createUrl
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'editUrl'
     */
    @Test
    public void editUrlTest() {
        // TODO: test editUrl
    }

    /**
     * Test the property 'moduleKey'
     */
    @Test
    public void moduleKeyTest() {
        // TODO: test moduleKey
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ruleKey'
     */
    @Test
    public void ruleKeyTest() {
        // TODO: test ruleKey
    }

    /**
     * Test the property 'ruleType'
     */
    @Test
    public void ruleTypeTest() {
        // TODO: test ruleType
    }

    /**
     * Test the property 'viewUrl'
     */
    @Test
    public void viewUrlTest() {
        // TODO: test viewUrl
    }

}
