/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AvailableWorkflowSystemRule
 */
public class AvailableWorkflowSystemRuleTest {
    private final AvailableWorkflowSystemRule model = new AvailableWorkflowSystemRule();

    /**
     * Model tests for AvailableWorkflowSystemRule
     */
    @Test
    public void testAvailableWorkflowSystemRule() {
        // TODO: test AvailableWorkflowSystemRule
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'incompatibleRuleKeys'
     */
    @Test
    public void incompatibleRuleKeysTest() {
        // TODO: test incompatibleRuleKeys
    }

    /**
     * Test the property 'isAvailableForInitialTransition'
     */
    @Test
    public void isAvailableForInitialTransitionTest() {
        // TODO: test isAvailableForInitialTransition
    }

    /**
     * Test the property 'isVisible'
     */
    @Test
    public void isVisibleTest() {
        // TODO: test isVisible
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ruleKey'
     */
    @Test
    public void ruleKeyTest() {
        // TODO: test ruleKey
    }

    /**
     * Test the property 'ruleType'
     */
    @Test
    public void ruleTypeTest() {
        // TODO: test ruleType
    }

}
