/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BulkOperationProgress
 */
public class BulkOperationProgressTest {
    private final BulkOperationProgress model = new BulkOperationProgress();

    /**
     * Model tests for BulkOperationProgress
     */
    @Test
    public void testBulkOperationProgress() {
        // TODO: test BulkOperationProgress
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'failedAccessibleIssues'
     */
    @Test
    public void failedAccessibleIssuesTest() {
        // TODO: test failedAccessibleIssues
    }

    /**
     * Test the property 'invalidOrInaccessibleIssueCount'
     */
    @Test
    public void invalidOrInaccessibleIssueCountTest() {
        // TODO: test invalidOrInaccessibleIssueCount
    }

    /**
     * Test the property 'processedAccessibleIssues'
     */
    @Test
    public void processedAccessibleIssuesTest() {
        // TODO: test processedAccessibleIssues
    }

    /**
     * Test the property 'progressPercent'
     */
    @Test
    public void progressPercentTest() {
        // TODO: test progressPercent
    }

    /**
     * Test the property 'started'
     */
    @Test
    public void startedTest() {
        // TODO: test started
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'submittedBy'
     */
    @Test
    public void submittedByTest() {
        // TODO: test submittedBy
    }

    /**
     * Test the property 'taskId'
     */
    @Test
    public void taskIdTest() {
        // TODO: test taskId
    }

    /**
     * Test the property 'totalIssueCount'
     */
    @Test
    public void totalIssueCountTest() {
        // TODO: test totalIssueCount
    }

    /**
     * Test the property 'updated'
     */
    @Test
    public void updatedTest() {
        // TODO: test updated
    }

}
