/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BulkChangeOwnerDetails
 */
public class BulkChangeOwnerDetailsTest {
    private final BulkChangeOwnerDetails model = new BulkChangeOwnerDetails();

    /**
     * Model tests for BulkChangeOwnerDetails
     */
    @Test
    public void testBulkChangeOwnerDetails() {
        // TODO: test BulkChangeOwnerDetails
    }

    /**
     * Test the property 'autofixName'
     */
    @Test
    public void autofixNameTest() {
        // TODO: test autofixName
    }

    /**
     * Test the property 'newOwner'
     */
    @Test
    public void newOwnerTest() {
        // TODO: test newOwner
    }

}
