/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.JsonTypeBean;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FieldCreateMetadata
 */
public class FieldCreateMetadataTest {
    private final FieldCreateMetadata model = new FieldCreateMetadata();

    /**
     * Model tests for FieldCreateMetadata
     */
    @Test
    public void testFieldCreateMetadata() {
        // TODO: test FieldCreateMetadata
    }

    /**
     * Test the property 'allowedValues'
     */
    @Test
    public void allowedValuesTest() {
        // TODO: test allowedValues
    }

    /**
     * Test the property 'autoCompleteUrl'
     */
    @Test
    public void autoCompleteUrlTest() {
        // TODO: test autoCompleteUrl
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

    /**
     * Test the property 'defaultValue'
     */
    @Test
    public void defaultValueTest() {
        // TODO: test defaultValue
    }

    /**
     * Test the property 'fieldId'
     */
    @Test
    public void fieldIdTest() {
        // TODO: test fieldId
    }

    /**
     * Test the property 'hasDefaultValue'
     */
    @Test
    public void hasDefaultValueTest() {
        // TODO: test hasDefaultValue
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'operations'
     */
    @Test
    public void operationsTest() {
        // TODO: test operations
    }

    /**
     * Test the property 'required'
     */
    @Test
    public void requiredTest() {
        // TODO: test required
    }

    /**
     * Test the property 'schema'
     */
    @Test
    public void schemaTest() {
        // TODO: test schema
    }

}
