/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.JiraCascadingSelectField;
import org.openapitools.client.model.JiraColorField;
import org.openapitools.client.model.JiraDateField;
import org.openapitools.client.model.JiraDateTimeField;
import org.openapitools.client.model.JiraIssueTypeField;
import org.openapitools.client.model.JiraLabelsField;
import org.openapitools.client.model.JiraMultiSelectComponentField;
import org.openapitools.client.model.JiraMultipleGroupPickerField;
import org.openapitools.client.model.JiraMultipleSelectField;
import org.openapitools.client.model.JiraMultipleSelectUserPickerField;
import org.openapitools.client.model.JiraMultipleVersionPickerField;
import org.openapitools.client.model.JiraNumberField;
import org.openapitools.client.model.JiraPriorityField;
import org.openapitools.client.model.JiraRichTextField;
import org.openapitools.client.model.JiraSingleGroupPickerField;
import org.openapitools.client.model.JiraSingleLineTextField;
import org.openapitools.client.model.JiraSingleSelectField;
import org.openapitools.client.model.JiraSingleSelectUserPickerField;
import org.openapitools.client.model.JiraSingleVersionPickerField;
import org.openapitools.client.model.JiraUrlField;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JiraIssueFields
 */
public class JiraIssueFieldsTest {
    private final JiraIssueFields model = new JiraIssueFields();

    /**
     * Model tests for JiraIssueFields
     */
    @Test
    public void testJiraIssueFields() {
        // TODO: test JiraIssueFields
    }

    /**
     * Test the property 'cascadingSelectFields'
     */
    @Test
    public void cascadingSelectFieldsTest() {
        // TODO: test cascadingSelectFields
    }

    /**
     * Test the property 'clearableNumberFields'
     */
    @Test
    public void clearableNumberFieldsTest() {
        // TODO: test clearableNumberFields
    }

    /**
     * Test the property 'colorFields'
     */
    @Test
    public void colorFieldsTest() {
        // TODO: test colorFields
    }

    /**
     * Test the property 'datePickerFields'
     */
    @Test
    public void datePickerFieldsTest() {
        // TODO: test datePickerFields
    }

    /**
     * Test the property 'dateTimePickerFields'
     */
    @Test
    public void dateTimePickerFieldsTest() {
        // TODO: test dateTimePickerFields
    }

    /**
     * Test the property 'issueType'
     */
    @Test
    public void issueTypeTest() {
        // TODO: test issueType
    }

    /**
     * Test the property 'labelsFields'
     */
    @Test
    public void labelsFieldsTest() {
        // TODO: test labelsFields
    }

    /**
     * Test the property 'multipleGroupPickerFields'
     */
    @Test
    public void multipleGroupPickerFieldsTest() {
        // TODO: test multipleGroupPickerFields
    }

    /**
     * Test the property 'multipleSelectClearableUserPickerFields'
     */
    @Test
    public void multipleSelectClearableUserPickerFieldsTest() {
        // TODO: test multipleSelectClearableUserPickerFields
    }

    /**
     * Test the property 'multipleSelectFields'
     */
    @Test
    public void multipleSelectFieldsTest() {
        // TODO: test multipleSelectFields
    }

    /**
     * Test the property 'multipleVersionPickerFields'
     */
    @Test
    public void multipleVersionPickerFieldsTest() {
        // TODO: test multipleVersionPickerFields
    }

    /**
     * Test the property 'multiselectComponents'
     */
    @Test
    public void multiselectComponentsTest() {
        // TODO: test multiselectComponents
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'richTextFields'
     */
    @Test
    public void richTextFieldsTest() {
        // TODO: test richTextFields
    }

    /**
     * Test the property 'singleGroupPickerFields'
     */
    @Test
    public void singleGroupPickerFieldsTest() {
        // TODO: test singleGroupPickerFields
    }

    /**
     * Test the property 'singleLineTextFields'
     */
    @Test
    public void singleLineTextFieldsTest() {
        // TODO: test singleLineTextFields
    }

    /**
     * Test the property 'singleSelectClearableUserPickerFields'
     */
    @Test
    public void singleSelectClearableUserPickerFieldsTest() {
        // TODO: test singleSelectClearableUserPickerFields
    }

    /**
     * Test the property 'singleSelectFields'
     */
    @Test
    public void singleSelectFieldsTest() {
        // TODO: test singleSelectFields
    }

    /**
     * Test the property 'singleVersionPickerFields'
     */
    @Test
    public void singleVersionPickerFieldsTest() {
        // TODO: test singleVersionPickerFields
    }

    /**
     * Test the property 'urlFields'
     */
    @Test
    public void urlFieldsTest() {
        // TODO: test urlFields
    }

}
