/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.JiraLabelsInput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JiraLabelsField
 */
public class JiraLabelsFieldTest {
    private final JiraLabelsField model = new JiraLabelsField();

    /**
     * Model tests for JiraLabelsField
     */
    @Test
    public void testJiraLabelsField() {
        // TODO: test JiraLabelsField
    }

    /**
     * Test the property 'bulkEditMultiSelectFieldOption'
     */
    @Test
    public void bulkEditMultiSelectFieldOptionTest() {
        // TODO: test bulkEditMultiSelectFieldOption
    }

    /**
     * Test the property 'fieldId'
     */
    @Test
    public void fieldIdTest() {
        // TODO: test fieldId
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

}
