/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PageBeanPriorityWithSequence;
import org.openapitools.client.model.PageBeanProjectDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PrioritySchemeWithPaginatedPrioritiesAndProjects
 */
public class PrioritySchemeWithPaginatedPrioritiesAndProjectsTest {
    private final PrioritySchemeWithPaginatedPrioritiesAndProjects model = new PrioritySchemeWithPaginatedPrioritiesAndProjects();

    /**
     * Model tests for PrioritySchemeWithPaginatedPrioritiesAndProjects
     */
    @Test
    public void testPrioritySchemeWithPaginatedPrioritiesAndProjects() {
        // TODO: test PrioritySchemeWithPaginatedPrioritiesAndProjects
    }

    /**
     * Test the property '_default'
     */
    @Test
    public void _defaultTest() {
        // TODO: test _default
    }

    /**
     * Test the property 'defaultPriorityId'
     */
    @Test
    public void defaultPriorityIdTest() {
        // TODO: test defaultPriorityId
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isDefault'
     */
    @Test
    public void isDefaultTest() {
        // TODO: test isDefault
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'priorities'
     */
    @Test
    public void prioritiesTest() {
        // TODO: test priorities
    }

    /**
     * Test the property 'projects'
     */
    @Test
    public void projectsTest() {
        // TODO: test projects
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

}
