/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProjectDataPolicy;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectWithDataPolicy
 */
public class ProjectWithDataPolicyTest {
    private final ProjectWithDataPolicy model = new ProjectWithDataPolicy();

    /**
     * Model tests for ProjectWithDataPolicy
     */
    @Test
    public void testProjectWithDataPolicy() {
        // TODO: test ProjectWithDataPolicy
    }

    /**
     * Test the property 'dataPolicy'
     */
    @Test
    public void dataPolicyTest() {
        // TODO: test dataPolicy
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
