/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.HealthCheckResult;
import org.openapitools.client.model.ServerInformationServerTimeZone;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServerInformation
 */
public class ServerInformationTest {
    private final ServerInformation model = new ServerInformation();

    /**
     * Model tests for ServerInformation
     */
    @Test
    public void testServerInformation() {
        // TODO: test ServerInformation
    }

    /**
     * Test the property 'baseUrl'
     */
    @Test
    public void baseUrlTest() {
        // TODO: test baseUrl
    }

    /**
     * Test the property 'buildDate'
     */
    @Test
    public void buildDateTest() {
        // TODO: test buildDate
    }

    /**
     * Test the property 'buildNumber'
     */
    @Test
    public void buildNumberTest() {
        // TODO: test buildNumber
    }

    /**
     * Test the property 'deploymentType'
     */
    @Test
    public void deploymentTypeTest() {
        // TODO: test deploymentType
    }

    /**
     * Test the property 'displayUrl'
     */
    @Test
    public void displayUrlTest() {
        // TODO: test displayUrl
    }

    /**
     * Test the property 'displayUrlConfluence'
     */
    @Test
    public void displayUrlConfluenceTest() {
        // TODO: test displayUrlConfluence
    }

    /**
     * Test the property 'displayUrlServicedeskHelpCenter'
     */
    @Test
    public void displayUrlServicedeskHelpCenterTest() {
        // TODO: test displayUrlServicedeskHelpCenter
    }

    /**
     * Test the property 'healthChecks'
     */
    @Test
    public void healthChecksTest() {
        // TODO: test healthChecks
    }

    /**
     * Test the property 'scmInfo'
     */
    @Test
    public void scmInfoTest() {
        // TODO: test scmInfo
    }

    /**
     * Test the property 'serverTime'
     */
    @Test
    public void serverTimeTest() {
        // TODO: test serverTime
    }

    /**
     * Test the property 'serverTimeZone'
     */
    @Test
    public void serverTimeZoneTest() {
        // TODO: test serverTimeZone
    }

    /**
     * Test the property 'serverTitle'
     */
    @Test
    public void serverTitleTest() {
        // TODO: test serverTitle
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'versionNumbers'
     */
    @Test
    public void versionNumbersTest() {
        // TODO: test versionNumbers
    }

}
