/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatusMigration
 */
public class StatusMigrationTest {
    private final StatusMigration model = new StatusMigration();

    /**
     * Model tests for StatusMigration
     */
    @Test
    public void testStatusMigration() {
        // TODO: test StatusMigration
    }

    /**
     * Test the property 'newStatusReference'
     */
    @Test
    public void newStatusReferenceTest() {
        // TODO: test newStatusReference
    }

    /**
     * Test the property 'oldStatusReference'
     */
    @Test
    public void oldStatusReferenceTest() {
        // TODO: test oldStatusReference
    }

}
