/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.SuggestedMappingsForPrioritiesRequestBean;
import org.openapitools.client.model.SuggestedMappingsForProjectsRequestBean;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SuggestedMappingsRequestBean
 */
public class SuggestedMappingsRequestBeanTest {
    private final SuggestedMappingsRequestBean model = new SuggestedMappingsRequestBean();

    /**
     * Model tests for SuggestedMappingsRequestBean
     */
    @Test
    public void testSuggestedMappingsRequestBean() {
        // TODO: test SuggestedMappingsRequestBean
    }

    /**
     * Test the property 'maxResults'
     */
    @Test
    public void maxResultsTest() {
        // TODO: test maxResults
    }

    /**
     * Test the property 'priorities'
     */
    @Test
    public void prioritiesTest() {
        // TODO: test priorities
    }

    /**
     * Test the property 'projects'
     */
    @Test
    public void projectsTest() {
        // TODO: test projects
    }

    /**
     * Test the property 'schemeId'
     */
    @Test
    public void schemeIdTest() {
        // TODO: test schemeId
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    public void startAtTest() {
        // TODO: test startAt
    }

}
