/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import org.openapitools.client.model.JiraWorkflow;
import org.openapitools.client.model.JiraWorkflowStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkflowReadResponse
 */
public class WorkflowReadResponseTest {
    private final WorkflowReadResponse model = new WorkflowReadResponse();

    /**
     * Model tests for WorkflowReadResponse
     */
    @Test
    public void testWorkflowReadResponse() {
        // TODO: test WorkflowReadResponse
    }

    /**
     * Test the property 'statuses'
     */
    @Test
    public void statusesTest() {
        // TODO: test statuses
    }

    /**
     * Test the property 'workflows'
     */
    @Test
    public void workflowsTest() {
        // TODO: test workflows
    }

}
