/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WorkflowMetadataRestModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkflowMetadataAndIssueTypeRestModel
 */
public class WorkflowMetadataAndIssueTypeRestModelTest {
    private final WorkflowMetadataAndIssueTypeRestModel model = new WorkflowMetadataAndIssueTypeRestModel();

    /**
     * Model tests for WorkflowMetadataAndIssueTypeRestModel
     */
    @Test
    public void testWorkflowMetadataAndIssueTypeRestModel() {
        // TODO: test WorkflowMetadataAndIssueTypeRestModel
    }

    /**
     * Test the property 'issueTypeIds'
     */
    @Test
    public void issueTypeIdsTest() {
        // TODO: test issueTypeIds
    }

    /**
     * Test the property 'workflow'
     */
    @Test
    public void workflowTest() {
        // TODO: test workflow
    }

}
