/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DocumentVersion;
import org.openapitools.client.model.StatusLayoutUpdate;
import org.openapitools.client.model.StatusMappingDTO;
import org.openapitools.client.model.StatusMigration;
import org.openapitools.client.model.TransitionUpdateDTO;
import org.openapitools.client.model.WorkflowLayout;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkflowUpdate
 */
public class WorkflowUpdateTest {
    private final WorkflowUpdate model = new WorkflowUpdate();

    /**
     * Model tests for WorkflowUpdate
     */
    @Test
    public void testWorkflowUpdate() {
        // TODO: test WorkflowUpdate
    }

    /**
     * Test the property 'defaultStatusMappings'
     */
    @Test
    public void defaultStatusMappingsTest() {
        // TODO: test defaultStatusMappings
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'startPointLayout'
     */
    @Test
    public void startPointLayoutTest() {
        // TODO: test startPointLayout
    }

    /**
     * Test the property 'statusMappings'
     */
    @Test
    public void statusMappingsTest() {
        // TODO: test statusMappings
    }

    /**
     * Test the property 'statuses'
     */
    @Test
    public void statusesTest() {
        // TODO: test statuses
    }

    /**
     * Test the property 'transitions'
     */
    @Test
    public void transitionsTest() {
        // TODO: test transitions
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
