/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProjectAndIssueTypePair;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkflowElementReference
 */
public class WorkflowElementReferenceTest {
    private final WorkflowElementReference model = new WorkflowElementReference();

    /**
     * Model tests for WorkflowElementReference
     */
    @Test
    public void testWorkflowElementReference() {
        // TODO: test WorkflowElementReference
    }

    /**
     * Test the property 'propertyKey'
     */
    @Test
    public void propertyKeyTest() {
        // TODO: test propertyKey
    }

    /**
     * Test the property 'ruleId'
     */
    @Test
    public void ruleIdTest() {
        // TODO: test ruleId
    }

    /**
     * Test the property 'statusMappingReference'
     */
    @Test
    public void statusMappingReferenceTest() {
        // TODO: test statusMappingReference
    }

    /**
     * Test the property 'statusReference'
     */
    @Test
    public void statusReferenceTest() {
        // TODO: test statusReference
    }

    /**
     * Test the property 'transitionId'
     */
    @Test
    public void transitionIdTest() {
        // TODO: test transitionId
    }

}
