/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WorkflowSchemeAssociation;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkflowSchemeUpdateRequiredMappingsRequest
 */
public class WorkflowSchemeUpdateRequiredMappingsRequestTest {
    private final WorkflowSchemeUpdateRequiredMappingsRequest model = new WorkflowSchemeUpdateRequiredMappingsRequest();

    /**
     * Model tests for WorkflowSchemeUpdateRequiredMappingsRequest
     */
    @Test
    public void testWorkflowSchemeUpdateRequiredMappingsRequest() {
        // TODO: test WorkflowSchemeUpdateRequiredMappingsRequest
    }

    /**
     * Test the property 'defaultWorkflowId'
     */
    @Test
    public void defaultWorkflowIdTest() {
        // TODO: test defaultWorkflowId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'workflowsForIssueTypes'
     */
    @Test
    public void workflowsForIssueTypesTest() {
        // TODO: test workflowsForIssueTypes
    }

}
