/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AvailableWorkflowConnectRule;
import org.openapitools.client.model.AvailableWorkflowForgeRule;
import org.openapitools.client.model.AvailableWorkflowSystemRule;
import org.openapitools.client.model.AvailableWorkflowTriggers;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkflowCapabilities
 */
public class WorkflowCapabilitiesTest {
    private final WorkflowCapabilities model = new WorkflowCapabilities();

    /**
     * Model tests for WorkflowCapabilities
     */
    @Test
    public void testWorkflowCapabilities() {
        // TODO: test WorkflowCapabilities
    }

    /**
     * Test the property 'connectRules'
     */
    @Test
    public void connectRulesTest() {
        // TODO: test connectRules
    }

    /**
     * Test the property 'editorScope'
     */
    @Test
    public void editorScopeTest() {
        // TODO: test editorScope
    }

    /**
     * Test the property 'forgeRules'
     */
    @Test
    public void forgeRulesTest() {
        // TODO: test forgeRules
    }

    /**
     * Test the property 'projectTypes'
     */
    @Test
    public void projectTypesTest() {
        // TODO: test projectTypes
    }

    /**
     * Test the property 'systemRules'
     */
    @Test
    public void systemRulesTest() {
        // TODO: test systemRules
    }

    /**
     * Test the property 'triggerRules'
     */
    @Test
    public void triggerRulesTest() {
        // TODO: test triggerRules
    }

}
