/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProjectAndIssueTypePair;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkflowReadRequest
 */
public class WorkflowReadRequestTest {
    private final WorkflowReadRequest model = new WorkflowReadRequest();

    /**
     * Model tests for WorkflowReadRequest
     */
    @Test
    public void testWorkflowReadRequest() {
        // TODO: test WorkflowReadRequest
    }

    /**
     * Test the property 'projectAndIssueTypes'
     */
    @Test
    public void projectAndIssueTypesTest() {
        // TODO: test projectAndIssueTypes
    }

    /**
     * Test the property 'workflowIds'
     */
    @Test
    public void workflowIdsTest() {
        // TODO: test workflowIds
    }

    /**
     * Test the property 'workflowNames'
     */
    @Test
    public void workflowNamesTest() {
        // TODO: test workflowNames
    }

}
