/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Errors;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Number of archived/unarchived issues and list of errors that occurred during the action, if any.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-30T14:27:49.596452195Z[Etc/UTC]", comments = "Generator version: 7.8.0-SNAPSHOT")
public class IssueArchivalSyncResponse {
  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private Errors errors;

  public static final String SERIALIZED_NAME_NUMBER_OF_ISSUES_UPDATED = "numberOfIssuesUpdated";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_ISSUES_UPDATED)
  private Long numberOfIssuesUpdated;

  public IssueArchivalSyncResponse() {
  }

  public IssueArchivalSyncResponse errors(Errors errors) {
    this.errors = errors;
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nullable
  public Errors getErrors() {
    return errors;
  }

  public void setErrors(Errors errors) {
    this.errors = errors;
  }


  public IssueArchivalSyncResponse numberOfIssuesUpdated(Long numberOfIssuesUpdated) {
    this.numberOfIssuesUpdated = numberOfIssuesUpdated;
    return this;
  }

  /**
   * Get numberOfIssuesUpdated
   * @return numberOfIssuesUpdated
   */
  @javax.annotation.Nullable
  public Long getNumberOfIssuesUpdated() {
    return numberOfIssuesUpdated;
  }

  public void setNumberOfIssuesUpdated(Long numberOfIssuesUpdated) {
    this.numberOfIssuesUpdated = numberOfIssuesUpdated;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueArchivalSyncResponse issueArchivalSyncResponse = (IssueArchivalSyncResponse) o;
    return Objects.equals(this.errors, issueArchivalSyncResponse.errors) &&
        Objects.equals(this.numberOfIssuesUpdated, issueArchivalSyncResponse.numberOfIssuesUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, numberOfIssuesUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueArchivalSyncResponse {\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    numberOfIssuesUpdated: ").append(toIndentedString(numberOfIssuesUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("errors");
    openapiFields.add("numberOfIssuesUpdated");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IssueArchivalSyncResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IssueArchivalSyncResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IssueArchivalSyncResponse is not found in the empty JSON string", IssueArchivalSyncResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IssueArchivalSyncResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IssueArchivalSyncResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `errors`
      if (jsonObj.get("errors") != null && !jsonObj.get("errors").isJsonNull()) {
        Errors.validateJsonElement(jsonObj.get("errors"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IssueArchivalSyncResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IssueArchivalSyncResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IssueArchivalSyncResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IssueArchivalSyncResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<IssueArchivalSyncResponse>() {
           @Override
           public void write(JsonWriter out, IssueArchivalSyncResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IssueArchivalSyncResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IssueArchivalSyncResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IssueArchivalSyncResponse
   * @throws IOException if the JSON string is invalid with respect to IssueArchivalSyncResponse
   */
  public static IssueArchivalSyncResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IssueArchivalSyncResponse.class);
  }

  /**
   * Convert an instance of IssueArchivalSyncResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

