/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ValidationOptionsForCreate;
import org.openapitools.client.model.WorkflowCreateRequest;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * WorkflowCreateValidateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-30T14:27:49.596452195Z[Etc/UTC]", comments = "Generator version: 7.8.0-SNAPSHOT")
public class WorkflowCreateValidateRequest {
  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  private WorkflowCreateRequest payload;

  public static final String SERIALIZED_NAME_VALIDATION_OPTIONS = "validationOptions";
  @SerializedName(SERIALIZED_NAME_VALIDATION_OPTIONS)
  private ValidationOptionsForCreate validationOptions;

  public WorkflowCreateValidateRequest() {
  }

  public WorkflowCreateValidateRequest payload(WorkflowCreateRequest payload) {
    this.payload = payload;
    return this;
  }

  /**
   * Get payload
   * @return payload
   */
  @javax.annotation.Nonnull
  public WorkflowCreateRequest getPayload() {
    return payload;
  }

  public void setPayload(WorkflowCreateRequest payload) {
    this.payload = payload;
  }


  public WorkflowCreateValidateRequest validationOptions(ValidationOptionsForCreate validationOptions) {
    this.validationOptions = validationOptions;
    return this;
  }

  /**
   * Get validationOptions
   * @return validationOptions
   */
  @javax.annotation.Nullable
  public ValidationOptionsForCreate getValidationOptions() {
    return validationOptions;
  }

  public void setValidationOptions(ValidationOptionsForCreate validationOptions) {
    this.validationOptions = validationOptions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowCreateValidateRequest workflowCreateValidateRequest = (WorkflowCreateValidateRequest) o;
    return Objects.equals(this.payload, workflowCreateValidateRequest.payload) &&
        Objects.equals(this.validationOptions, workflowCreateValidateRequest.validationOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payload, validationOptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowCreateValidateRequest {\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    validationOptions: ").append(toIndentedString(validationOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("payload");
    openapiFields.add("validationOptions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("payload");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WorkflowCreateValidateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WorkflowCreateValidateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WorkflowCreateValidateRequest is not found in the empty JSON string", WorkflowCreateValidateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WorkflowCreateValidateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WorkflowCreateValidateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WorkflowCreateValidateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `payload`
      WorkflowCreateRequest.validateJsonElement(jsonObj.get("payload"));
      // validate the optional field `validationOptions`
      if (jsonObj.get("validationOptions") != null && !jsonObj.get("validationOptions").isJsonNull()) {
        ValidationOptionsForCreate.validateJsonElement(jsonObj.get("validationOptions"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WorkflowCreateValidateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WorkflowCreateValidateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WorkflowCreateValidateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WorkflowCreateValidateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<WorkflowCreateValidateRequest>() {
           @Override
           public void write(JsonWriter out, WorkflowCreateValidateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WorkflowCreateValidateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WorkflowCreateValidateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WorkflowCreateValidateRequest
   * @throws IOException if the JSON string is invalid with respect to WorkflowCreateValidateRequest
   */
  public static WorkflowCreateValidateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WorkflowCreateValidateRequest.class);
  }

  /**
   * Convert an instance of WorkflowCreateValidateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

