/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorCollection;
import org.openapitools.client.model.ProjectDataPolicies;
import org.openapitools.client.model.WorkspaceDataPolicy;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppDataPoliciesApi
 */
@Disabled
public class AppDataPoliciesApiTest {

    private final AppDataPoliciesApi api = new AppDataPoliciesApi();

    /**
     * Get data policy for projects
     *
     * Returns data policies for the projects specified in the request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPoliciesTest() throws ApiException {
        String ids = null;
        ProjectDataPolicies response = api.getPolicies(ids);
        // TODO: test validations
    }

    /**
     * Get data policy for the workspace
     *
     * Returns data policy for the workspace.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPolicyTest() throws ApiException {
        WorkspaceDataPolicy response = api.getPolicy();
        // TODO: test validations
    }

}
