/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.EntityProperty;
import org.openapitools.client.model.OperationMessage;
import org.openapitools.client.model.PropertyKeys;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppPropertiesApi
 */
@Disabled
public class AppPropertiesApiTest {

    private final AppPropertiesApi api = new AppPropertiesApi();

    /**
     * Delete app property
     *
     * Deletes an app&#39;s property.  **[Permissions](#permissions) required:** Only a Connect app whose key matches &#x60;addonKey&#x60; can make this request. Additionally, Forge apps can access Connect app properties (stored against the same &#x60;app.connect.key&#x60;).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addonPropertiesResourceDeleteAddonPropertyDeleteTest() throws ApiException {
        String addonKey = null;
        String propertyKey = null;
        api.addonPropertiesResourceDeleteAddonPropertyDelete(addonKey, propertyKey);
        // TODO: test validations
    }

    /**
     * Get app properties
     *
     * Gets all the properties of an app.  **[Permissions](#permissions) required:** Only a Connect app whose key matches &#x60;addonKey&#x60; can make this request. Additionally, Forge apps can access Connect app properties (stored against the same &#x60;app.connect.key&#x60;).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addonPropertiesResourceGetAddonPropertiesGetTest() throws ApiException {
        String addonKey = null;
        PropertyKeys response = api.addonPropertiesResourceGetAddonPropertiesGet(addonKey);
        // TODO: test validations
    }

    /**
     * Get app property
     *
     * Returns the key and value of an app&#39;s property.  **[Permissions](#permissions) required:** Only a Connect app whose key matches &#x60;addonKey&#x60; can make this request. Additionally, Forge apps can access Connect app properties (stored against the same &#x60;app.connect.key&#x60;).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addonPropertiesResourceGetAddonPropertyGetTest() throws ApiException {
        String addonKey = null;
        String propertyKey = null;
        EntityProperty response = api.addonPropertiesResourceGetAddonPropertyGet(addonKey, propertyKey);
        // TODO: test validations
    }

    /**
     * Set app property
     *
     * Sets the value of an app&#39;s property. Use this resource to store custom data for your app.  The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.  **[Permissions](#permissions) required:** Only a Connect app whose key matches &#x60;addonKey&#x60; can make this request. Additionally, Forge apps can access Connect app properties (stored against the same &#x60;app.connect.key&#x60;).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addonPropertiesResourcePutAddonPropertyPutTest() throws ApiException {
        String addonKey = null;
        String propertyKey = null;
        Object body = null;
        OperationMessage response = api.addonPropertiesResourcePutAddonPropertyPut(addonKey, propertyKey, body);
        // TODO: test validations
    }

    /**
     * Delete app property (Forge)
     *
     * Deletes a Forge app&#39;s property.  **[Permissions](#permissions) required:** Only Forge apps can make this request.  The new &#x60;write:app-data:jira&#x60; OAuth scope is 100% optional now, and not using it won&#39;t break your app. However, we recommend adding it to your app&#39;s scope list because we will eventually make it mandatory.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteForgeAppPropertyTest() throws ApiException {
        String propertyKey = null;
        api.deleteForgeAppProperty(propertyKey);
        // TODO: test validations
    }

    /**
     * Set app property (Forge)
     *
     * Sets the value of a Forge app&#39;s property. These values can be retrieved in [Jira expressions](https://developer.atlassian.com/cloud/jira/platform/jira-expressions/) through the &#x60;app&#x60; [context variable](https://developer.atlassian.com/cloud/jira/platform/jira-expressions/#context-variables).  For other use cases, use the [Storage API](https://developer.atlassian.com/platform/forge/runtime-reference/storage-api/).  The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.  **[Permissions](#permissions) required:** Only Forge apps can make this request.  The new &#x60;write:app-data:jira&#x60; OAuth scope is 100% optional now, and not using it won&#39;t break your app. However, we recommend adding it to your app&#39;s scope list because we will eventually make it mandatory.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putForgeAppPropertyTest() throws ApiException {
        String propertyKey = null;
        Object body = null;
        OperationMessage response = api.putForgeAppProperty(propertyKey, body);
        // TODO: test validations
    }

}
