/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DataClassificationLevelsBean;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClassificationLevelsApi
 */
@Disabled
public class ClassificationLevelsApiTest {

    private final ClassificationLevelsApi api = new ClassificationLevelsApi();

    /**
     * Get all classification levels
     *
     * Returns all classification levels.  **[Permissions](#permissions) required:** None.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllUserDataClassificationLevelsTest() throws ApiException {
        Set<String> status = null;
        String orderBy = null;
        DataClassificationLevelsBean response = api.getAllUserDataClassificationLevels(status, orderBy);
        // TODO: test validations
    }

}
