/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CustomFieldValueUpdateDetails;
import org.openapitools.client.model.MultipleCustomFieldValuesUpdateDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IssueCustomFieldValuesAppsApi
 */
@Disabled
public class IssueCustomFieldValuesAppsApiTest {

    private final IssueCustomFieldValuesAppsApi api = new IssueCustomFieldValuesAppsApi();

    /**
     * Update custom field value
     *
     * Updates the value of a custom field on one or more issues.  Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.  **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.  The new &#x60;write:app-data:jira&#x60; OAuth scope is 100% optional now, and not using it won&#39;t break your app. However, we recommend adding it to your app&#39;s scope list because we will eventually make it mandatory.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCustomFieldValueTest() throws ApiException {
        String fieldIdOrKey = null;
        CustomFieldValueUpdateDetails customFieldValueUpdateDetails = null;
        Boolean generateChangelog = null;
        Object response = api.updateCustomFieldValue(fieldIdOrKey, customFieldValueUpdateDetails, generateChangelog);
        // TODO: test validations
    }

    /**
     * Update custom fields
     *
     * Updates the value of one or more custom fields on one or more issues. Combinations of custom field and issue should be unique within the request.  Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.  **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.  The new &#x60;write:app-data:jira&#x60; OAuth scope is 100% optional now, and not using it won&#39;t break your app. However, we recommend adding it to your app&#39;s scope list because we will eventually make it mandatory.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateMultipleCustomFieldValuesTest() throws ApiException {
        MultipleCustomFieldValuesUpdateDetails multipleCustomFieldValuesUpdateDetails = null;
        Boolean generateChangelog = null;
        Object response = api.updateMultipleCustomFieldValues(multipleCustomFieldValuesUpdateDetails, generateChangelog);
        // TODO: test validations
    }

}
