/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorCollection;
import org.openapitools.client.model.License;
import org.openapitools.client.model.LicenseMetric;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LicenseMetricsApi
 */
@Disabled
public class LicenseMetricsApiTest {

    private final LicenseMetricsApi api = new LicenseMetricsApi();

    /**
     * Get approximate application license count
     *
     * Returns the total approximate number of user accounts for a single Jira license. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getApproximateApplicationLicenseCountTest() throws ApiException {
        String applicationKey = null;
        LicenseMetric response = api.getApproximateApplicationLicenseCount(applicationKey);
        // TODO: test validations
    }

    /**
     * Get approximate license count
     *
     * Returns the approximate number of user accounts across all Jira licenses. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getApproximateLicenseCountTest() throws ApiException {
        LicenseMetric response = api.getApproximateLicenseCount();
        // TODO: test validations
    }

    /**
     * Get license
     *
     * Returns licensing information about the Jira instance.  **[Permissions](#permissions) required:** None.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLicenseTest() throws ApiException {
        License response = api.getLicense();
        // TODO: test validations
    }

}
