/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.UpdateDefaultProjectClassificationBean;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectClassificationLevelsApi
 */
@Disabled
public class ProjectClassificationLevelsApiTest {

    private final ProjectClassificationLevelsApi api = new ProjectClassificationLevelsApi();

    /**
     * Get the default data classification level of a project
     *
     * Returns the default data classification for a project.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDefaultProjectClassificationTest() throws ApiException {
        String projectIdOrKey = null;
        Object response = api.getDefaultProjectClassification(projectIdOrKey);
        // TODO: test validations
    }

    /**
     * Remove the default data classification level from a project
     *
     * Remove the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeDefaultProjectClassificationTest() throws ApiException {
        String projectIdOrKey = null;
        Object response = api.removeDefaultProjectClassification(projectIdOrKey);
        // TODO: test validations
    }

    /**
     * Update the default data classification level of a project
     *
     * Updates the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateDefaultProjectClassificationTest() throws ApiException {
        String projectIdOrKey = null;
        UpdateDefaultProjectClassificationBean updateDefaultProjectClassificationBean = null;
        Object response = api.updateDefaultProjectClassification(projectIdOrKey, updateDefaultProjectClassificationBean);
        // TODO: test validations
    }

}
