/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-df7582dfe7cda5bf12b0b05c137e574248cecd69
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ServiceRegistry;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceRegistryApi
 */
@Disabled
public class ServiceRegistryApiTest {

    private final ServiceRegistryApi api = new ServiceRegistryApi();

    /**
     * Retrieve the attributes of service registries
     *
     * Retrieve the attributes of given service registries.  **[Permissions](#permissions) required:** Only Connect apps can make this request and the servicesIds belong to the tenant you are requesting
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceRegistryResourceServicesGetTest() throws ApiException {
        List<String> serviceIds = null;
        List<ServiceRegistry> response = api.serviceRegistryResourceServicesGet(serviceIds);
        // TODO: test validations
    }

}
